// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnemyInfoTest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_EnemyInfoTest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_EnemyInfoTest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_EnemyInfoTest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_EnemyInfoTest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EnemyInfoTest_2eproto;
namespace HiProtobuf {
class EnemyInfoTest;
class EnemyInfoTestDefaultTypeInternal;
extern EnemyInfoTestDefaultTypeInternal _EnemyInfoTest_default_instance_;
class Excel_EnemyInfoTest;
class Excel_EnemyInfoTestDefaultTypeInternal;
extern Excel_EnemyInfoTestDefaultTypeInternal _Excel_EnemyInfoTest_default_instance_;
}  // namespace HiProtobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::HiProtobuf::EnemyInfoTest* Arena::CreateMaybeMessage<::HiProtobuf::EnemyInfoTest>(Arena*);
template<> ::HiProtobuf::Excel_EnemyInfoTest* Arena::CreateMaybeMessage<::HiProtobuf::Excel_EnemyInfoTest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HiProtobuf {

// ===================================================================

class EnemyInfoTest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HiProtobuf.EnemyInfoTest) */ {
 public:
  EnemyInfoTest();
  virtual ~EnemyInfoTest();

  EnemyInfoTest(const EnemyInfoTest& from);
  EnemyInfoTest(EnemyInfoTest&& from) noexcept
    : EnemyInfoTest() {
    *this = ::std::move(from);
  }

  inline EnemyInfoTest& operator=(const EnemyInfoTest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnemyInfoTest& operator=(EnemyInfoTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EnemyInfoTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnemyInfoTest* internal_default_instance() {
    return reinterpret_cast<const EnemyInfoTest*>(
               &_EnemyInfoTest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(EnemyInfoTest* other);
  friend void swap(EnemyInfoTest& a, EnemyInfoTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EnemyInfoTest* New() const final {
    return CreateMaybeMessage<EnemyInfoTest>(nullptr);
  }

  EnemyInfoTest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnemyInfoTest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EnemyInfoTest& from);
  void MergeFrom(const EnemyInfoTest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnemyInfoTest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HiProtobuf.EnemyInfoTest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_EnemyInfoTest_2eproto);
    return ::descriptor_table_EnemyInfoTest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // string RootPath = 3;
  void clear_rootpath();
  static const int kRootPathFieldNumber = 3;
  const std::string& rootpath() const;
  void set_rootpath(const std::string& value);
  void set_rootpath(std::string&& value);
  void set_rootpath(const char* value);
  void set_rootpath(const char* value, size_t size);
  std::string* mutable_rootpath();
  std::string* release_rootpath();
  void set_allocated_rootpath(std::string* rootpath);

  // string Path = 4;
  void clear_path();
  static const int kPathFieldNumber = 4;
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);

  // uint32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:HiProtobuf.EnemyInfoTest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rootpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_EnemyInfoTest_2eproto;
};
// -------------------------------------------------------------------

class Excel_EnemyInfoTest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HiProtobuf.Excel_EnemyInfoTest) */ {
 public:
  Excel_EnemyInfoTest();
  virtual ~Excel_EnemyInfoTest();

  Excel_EnemyInfoTest(const Excel_EnemyInfoTest& from);
  Excel_EnemyInfoTest(Excel_EnemyInfoTest&& from) noexcept
    : Excel_EnemyInfoTest() {
    *this = ::std::move(from);
  }

  inline Excel_EnemyInfoTest& operator=(const Excel_EnemyInfoTest& from) {
    CopyFrom(from);
    return *this;
  }
  inline Excel_EnemyInfoTest& operator=(Excel_EnemyInfoTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Excel_EnemyInfoTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Excel_EnemyInfoTest* internal_default_instance() {
    return reinterpret_cast<const Excel_EnemyInfoTest*>(
               &_Excel_EnemyInfoTest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Excel_EnemyInfoTest* other);
  friend void swap(Excel_EnemyInfoTest& a, Excel_EnemyInfoTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Excel_EnemyInfoTest* New() const final {
    return CreateMaybeMessage<Excel_EnemyInfoTest>(nullptr);
  }

  Excel_EnemyInfoTest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Excel_EnemyInfoTest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Excel_EnemyInfoTest& from);
  void MergeFrom(const Excel_EnemyInfoTest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Excel_EnemyInfoTest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HiProtobuf.Excel_EnemyInfoTest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_EnemyInfoTest_2eproto);
    return ::descriptor_table_EnemyInfoTest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .HiProtobuf.EnemyInfoTest Data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  ::HiProtobuf::EnemyInfoTest* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfoTest >*
      mutable_data();
  const ::HiProtobuf::EnemyInfoTest& data(int index) const;
  ::HiProtobuf::EnemyInfoTest* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfoTest >&
      data() const;

  // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_EnemyInfoTest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfoTest > data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_EnemyInfoTest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EnemyInfoTest

// uint32 ID = 1;
inline void EnemyInfoTest::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EnemyInfoTest::id() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfoTest.ID)
  return id_;
}
inline void EnemyInfoTest::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfoTest.ID)
}

// string Name = 2;
inline void EnemyInfoTest::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfoTest::name() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfoTest.Name)
  return name_.GetNoArena();
}
inline void EnemyInfoTest::set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfoTest.Name)
}
inline void EnemyInfoTest::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfoTest.Name)
}
inline void EnemyInfoTest::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfoTest.Name)
}
inline void EnemyInfoTest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfoTest.Name)
}
inline std::string* EnemyInfoTest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfoTest.Name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfoTest::release_name() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfoTest.Name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfoTest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfoTest.Name)
}

// string RootPath = 3;
inline void EnemyInfoTest::clear_rootpath() {
  rootpath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfoTest::rootpath() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfoTest.RootPath)
  return rootpath_.GetNoArena();
}
inline void EnemyInfoTest::set_rootpath(const std::string& value) {
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfoTest.RootPath)
}
inline void EnemyInfoTest::set_rootpath(std::string&& value) {
  
  rootpath_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfoTest.RootPath)
}
inline void EnemyInfoTest::set_rootpath(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfoTest.RootPath)
}
inline void EnemyInfoTest::set_rootpath(const char* value, size_t size) {
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfoTest.RootPath)
}
inline std::string* EnemyInfoTest::mutable_rootpath() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfoTest.RootPath)
  return rootpath_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfoTest::release_rootpath() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfoTest.RootPath)
  
  return rootpath_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfoTest::set_allocated_rootpath(std::string* rootpath) {
  if (rootpath != nullptr) {
    
  } else {
    
  }
  rootpath_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rootpath);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfoTest.RootPath)
}

// string Path = 4;
inline void EnemyInfoTest::clear_path() {
  path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfoTest::path() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfoTest.Path)
  return path_.GetNoArena();
}
inline void EnemyInfoTest::set_path(const std::string& value) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfoTest.Path)
}
inline void EnemyInfoTest::set_path(std::string&& value) {
  
  path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfoTest.Path)
}
inline void EnemyInfoTest::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfoTest.Path)
}
inline void EnemyInfoTest::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfoTest.Path)
}
inline std::string* EnemyInfoTest::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfoTest.Path)
  return path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfoTest::release_path() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfoTest.Path)
  
  return path_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfoTest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfoTest.Path)
}

// -------------------------------------------------------------------

// Excel_EnemyInfoTest

// repeated .HiProtobuf.EnemyInfoTest Data = 1;
inline int Excel_EnemyInfoTest::data_size() const {
  return data_.size();
}
inline void Excel_EnemyInfoTest::clear_data() {
  data_.Clear();
}
inline ::HiProtobuf::EnemyInfoTest* Excel_EnemyInfoTest::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:HiProtobuf.Excel_EnemyInfoTest.Data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfoTest >*
Excel_EnemyInfoTest::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:HiProtobuf.Excel_EnemyInfoTest.Data)
  return &data_;
}
inline const ::HiProtobuf::EnemyInfoTest& Excel_EnemyInfoTest::data(int index) const {
  // @@protoc_insertion_point(field_get:HiProtobuf.Excel_EnemyInfoTest.Data)
  return data_.Get(index);
}
inline ::HiProtobuf::EnemyInfoTest* Excel_EnemyInfoTest::add_data() {
  // @@protoc_insertion_point(field_add:HiProtobuf.Excel_EnemyInfoTest.Data)
  return data_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfoTest >&
Excel_EnemyInfoTest::data() const {
  // @@protoc_insertion_point(field_list:HiProtobuf.Excel_EnemyInfoTest.Data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HiProtobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_EnemyInfoTest_2eproto
