// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnemyInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_EnemyInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_EnemyInfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_EnemyInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_EnemyInfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_EnemyInfo_2eproto;
namespace HiProtobuf {
class EnemyInfo;
class EnemyInfoDefaultTypeInternal;
extern EnemyInfoDefaultTypeInternal _EnemyInfo_default_instance_;
class Excel_EnemyInfo;
class Excel_EnemyInfoDefaultTypeInternal;
extern Excel_EnemyInfoDefaultTypeInternal _Excel_EnemyInfo_default_instance_;
}  // namespace HiProtobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::HiProtobuf::EnemyInfo* Arena::CreateMaybeMessage<::HiProtobuf::EnemyInfo>(Arena*);
template<> ::HiProtobuf::Excel_EnemyInfo* Arena::CreateMaybeMessage<::HiProtobuf::Excel_EnemyInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace HiProtobuf {

// ===================================================================

class EnemyInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HiProtobuf.EnemyInfo) */ {
 public:
  EnemyInfo();
  virtual ~EnemyInfo();

  EnemyInfo(const EnemyInfo& from);
  EnemyInfo(EnemyInfo&& from) noexcept
    : EnemyInfo() {
    *this = ::std::move(from);
  }

  inline EnemyInfo& operator=(const EnemyInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnemyInfo& operator=(EnemyInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EnemyInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnemyInfo* internal_default_instance() {
    return reinterpret_cast<const EnemyInfo*>(
               &_EnemyInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(EnemyInfo* other);
  friend void swap(EnemyInfo& a, EnemyInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EnemyInfo* New() const final {
    return CreateMaybeMessage<EnemyInfo>(nullptr);
  }

  EnemyInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnemyInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EnemyInfo& from);
  void MergeFrom(const EnemyInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnemyInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HiProtobuf.EnemyInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_EnemyInfo_2eproto);
    return ::descriptor_table_EnemyInfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // string RootPath = 3;
  void clear_rootpath();
  static const int kRootPathFieldNumber = 3;
  const std::string& rootpath() const;
  void set_rootpath(const std::string& value);
  void set_rootpath(std::string&& value);
  void set_rootpath(const char* value);
  void set_rootpath(const char* value, size_t size);
  std::string* mutable_rootpath();
  std::string* release_rootpath();
  void set_allocated_rootpath(std::string* rootpath);

  // string Path = 4;
  void clear_path();
  static const int kPathFieldNumber = 4;
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);

  // uint32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:HiProtobuf.EnemyInfo)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rootpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_EnemyInfo_2eproto;
};
// -------------------------------------------------------------------

class Excel_EnemyInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HiProtobuf.Excel_EnemyInfo) */ {
 public:
  Excel_EnemyInfo();
  virtual ~Excel_EnemyInfo();

  Excel_EnemyInfo(const Excel_EnemyInfo& from);
  Excel_EnemyInfo(Excel_EnemyInfo&& from) noexcept
    : Excel_EnemyInfo() {
    *this = ::std::move(from);
  }

  inline Excel_EnemyInfo& operator=(const Excel_EnemyInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline Excel_EnemyInfo& operator=(Excel_EnemyInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Excel_EnemyInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Excel_EnemyInfo* internal_default_instance() {
    return reinterpret_cast<const Excel_EnemyInfo*>(
               &_Excel_EnemyInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Excel_EnemyInfo* other);
  friend void swap(Excel_EnemyInfo& a, Excel_EnemyInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Excel_EnemyInfo* New() const final {
    return CreateMaybeMessage<Excel_EnemyInfo>(nullptr);
  }

  Excel_EnemyInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Excel_EnemyInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Excel_EnemyInfo& from);
  void MergeFrom(const Excel_EnemyInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Excel_EnemyInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HiProtobuf.Excel_EnemyInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_EnemyInfo_2eproto);
    return ::descriptor_table_EnemyInfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .HiProtobuf.EnemyInfo Data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  ::HiProtobuf::EnemyInfo* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfo >*
      mutable_data();
  const ::HiProtobuf::EnemyInfo& data(int index) const;
  ::HiProtobuf::EnemyInfo* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfo >&
      data() const;

  // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_EnemyInfo)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfo > data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_EnemyInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EnemyInfo

// uint32 ID = 1;
inline void EnemyInfo::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 EnemyInfo::id() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfo.ID)
  return id_;
}
inline void EnemyInfo::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfo.ID)
}

// string Name = 2;
inline void EnemyInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfo::name() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfo.Name)
  return name_.GetNoArena();
}
inline void EnemyInfo::set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfo.Name)
}
inline void EnemyInfo::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfo.Name)
}
inline void EnemyInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfo.Name)
}
inline void EnemyInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfo.Name)
}
inline std::string* EnemyInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfo.Name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfo::release_name() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfo.Name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfo::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfo.Name)
}

// string RootPath = 3;
inline void EnemyInfo::clear_rootpath() {
  rootpath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfo::rootpath() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfo.RootPath)
  return rootpath_.GetNoArena();
}
inline void EnemyInfo::set_rootpath(const std::string& value) {
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfo.RootPath)
}
inline void EnemyInfo::set_rootpath(std::string&& value) {
  
  rootpath_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfo.RootPath)
}
inline void EnemyInfo::set_rootpath(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfo.RootPath)
}
inline void EnemyInfo::set_rootpath(const char* value, size_t size) {
  
  rootpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfo.RootPath)
}
inline std::string* EnemyInfo::mutable_rootpath() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfo.RootPath)
  return rootpath_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfo::release_rootpath() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfo.RootPath)
  
  return rootpath_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfo::set_allocated_rootpath(std::string* rootpath) {
  if (rootpath != nullptr) {
    
  } else {
    
  }
  rootpath_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rootpath);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfo.RootPath)
}

// string Path = 4;
inline void EnemyInfo::clear_path() {
  path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& EnemyInfo::path() const {
  // @@protoc_insertion_point(field_get:HiProtobuf.EnemyInfo.Path)
  return path_.GetNoArena();
}
inline void EnemyInfo::set_path(const std::string& value) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HiProtobuf.EnemyInfo.Path)
}
inline void EnemyInfo::set_path(std::string&& value) {
  
  path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HiProtobuf.EnemyInfo.Path)
}
inline void EnemyInfo::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HiProtobuf.EnemyInfo.Path)
}
inline void EnemyInfo::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HiProtobuf.EnemyInfo.Path)
}
inline std::string* EnemyInfo::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:HiProtobuf.EnemyInfo.Path)
  return path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* EnemyInfo::release_path() {
  // @@protoc_insertion_point(field_release:HiProtobuf.EnemyInfo.Path)
  
  return path_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void EnemyInfo::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:HiProtobuf.EnemyInfo.Path)
}

// -------------------------------------------------------------------

// Excel_EnemyInfo

// repeated .HiProtobuf.EnemyInfo Data = 1;
inline int Excel_EnemyInfo::data_size() const {
  return data_.size();
}
inline void Excel_EnemyInfo::clear_data() {
  data_.Clear();
}
inline ::HiProtobuf::EnemyInfo* Excel_EnemyInfo::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:HiProtobuf.Excel_EnemyInfo.Data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfo >*
Excel_EnemyInfo::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:HiProtobuf.Excel_EnemyInfo.Data)
  return &data_;
}
inline const ::HiProtobuf::EnemyInfo& Excel_EnemyInfo::data(int index) const {
  // @@protoc_insertion_point(field_get:HiProtobuf.Excel_EnemyInfo.Data)
  return data_.Get(index);
}
inline ::HiProtobuf::EnemyInfo* Excel_EnemyInfo::add_data() {
  // @@protoc_insertion_point(field_add:HiProtobuf.Excel_EnemyInfo.Data)
  return data_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::HiProtobuf::EnemyInfo >&
Excel_EnemyInfo::data() const {
  // @@protoc_insertion_point(field_list:HiProtobuf.Excel_EnemyInfo.Data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace HiProtobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_EnemyInfo_2eproto
