// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnemyInfoTest.proto

package com.HiProtobuf.HiProtobuf;

public final class EnemyInfoTest_classname {
  private EnemyInfoTest_classname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnemyInfoTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.EnemyInfoTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 ID = 1;</code>
     */
    int getID();

    /**
     * <code>string Name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string RootPath = 3;</code>
     */
    java.lang.String getRootPath();
    /**
     * <code>string RootPath = 3;</code>
     */
    com.google.protobuf.ByteString
        getRootPathBytes();

    /**
     * <code>string Path = 4;</code>
     */
    java.lang.String getPath();
    /**
     * <code>string Path = 4;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code HiProtobuf.EnemyInfoTest}
   */
  public  static final class EnemyInfoTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.EnemyInfoTest)
      EnemyInfoTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnemyInfoTest.newBuilder() to construct.
    private EnemyInfoTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnemyInfoTest() {
      name_ = "";
      rootPath_ = "";
      path_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EnemyInfoTest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnemyInfoTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              iD_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              rootPath_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_EnemyInfoTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_EnemyInfoTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.class, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    /**
     * <code>uint32 ID = 1;</code>
     */
    public int getID() {
      return iD_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string Name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOTPATH_FIELD_NUMBER = 3;
    private volatile java.lang.Object rootPath_;
    /**
     * <code>string RootPath = 3;</code>
     */
    public java.lang.String getRootPath() {
      java.lang.Object ref = rootPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rootPath_ = s;
        return s;
      }
    }
    /**
     * <code>string RootPath = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRootPathBytes() {
      java.lang.Object ref = rootPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rootPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object path_;
    /**
     * <code>string Path = 4;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string Path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0) {
        output.writeUInt32(1, iD_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getRootPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rootPath_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, path_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, iD_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getRootPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rootPath_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest other = (com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest) obj;

      if (getID()
          != other.getID()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getRootPath()
          .equals(other.getRootPath())) return false;
      if (!getPath()
          .equals(other.getPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ROOTPATH_FIELD_NUMBER;
      hash = (53 * hash) + getRootPath().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.EnemyInfoTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.EnemyInfoTest)
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_EnemyInfoTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_EnemyInfoTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.class, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        iD_ = 0;

        name_ = "";

        rootPath_ = "";

        path_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_EnemyInfoTest_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest build() {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest buildPartial() {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest result = new com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest(this);
        result.iD_ = iD_;
        result.name_ = name_;
        result.rootPath_ = rootPath_;
        result.path_ = path_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest other) {
        if (other == com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.getDefaultInstance()) return this;
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getRootPath().isEmpty()) {
          rootPath_ = other.rootPath_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iD_ ;
      /**
       * <code>uint32 ID = 1;</code>
       */
      public int getID() {
        return iD_;
      }
      /**
       * <code>uint32 ID = 1;</code>
       */
      public Builder setID(int value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ID = 1;</code>
       */
      public Builder clearID() {
        
        iD_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string Name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rootPath_ = "";
      /**
       * <code>string RootPath = 3;</code>
       */
      public java.lang.String getRootPath() {
        java.lang.Object ref = rootPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rootPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RootPath = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRootPathBytes() {
        java.lang.Object ref = rootPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rootPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RootPath = 3;</code>
       */
      public Builder setRootPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rootPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RootPath = 3;</code>
       */
      public Builder clearRootPath() {
        
        rootPath_ = getDefaultInstance().getRootPath();
        onChanged();
        return this;
      }
      /**
       * <code>string RootPath = 3;</code>
       */
      public Builder setRootPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rootPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string Path = 4;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Path = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Path = 4;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Path = 4;</code>
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string Path = 4;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.EnemyInfoTest)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.EnemyInfoTest)
    private static final com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest();
    }

    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnemyInfoTest>
        PARSER = new com.google.protobuf.AbstractParser<EnemyInfoTest>() {
      @java.lang.Override
      public EnemyInfoTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnemyInfoTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnemyInfoTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnemyInfoTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Excel_EnemyInfoTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Excel_EnemyInfoTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> 
        getDataList();
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getData(int index);
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    java.util.List<? extends com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HiProtobuf.Excel_EnemyInfoTest}
   */
  public  static final class Excel_EnemyInfoTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Excel_EnemyInfoTest)
      Excel_EnemyInfoTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Excel_EnemyInfoTest.newBuilder() to construct.
    private Excel_EnemyInfoTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Excel_EnemyInfoTest() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Excel_EnemyInfoTest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Excel_EnemyInfoTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_Excel_EnemyInfoTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.class, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> data_;
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    public java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    public java.util.List<? extends com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
     */
    public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest other = (com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest) obj;

      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Excel_EnemyInfoTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Excel_EnemyInfoTest)
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_Excel_EnemyInfoTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.class, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest build() {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest buildPartial() {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest result = new com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest other) {
        if (other == com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder> dataBuilder_;

      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder setData(
          int index, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder setData(
          int index, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder addData(com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder addData(
          int index, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder addData(
          com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder addData(
          int index, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public java.util.List<? extends com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.getDefaultInstance());
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.getDefaultInstance());
      }
      /**
       * <code>repeated .HiProtobuf.EnemyInfoTest Data = 1;</code>
       */
      public java.util.List<com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTest.Builder, com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.EnemyInfoTestOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Excel_EnemyInfoTest)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_EnemyInfoTest)
    private static final com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest();
    }

    public static com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Excel_EnemyInfoTest>
        PARSER = new com.google.protobuf.AbstractParser<Excel_EnemyInfoTest>() {
      @java.lang.Override
      public Excel_EnemyInfoTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Excel_EnemyInfoTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Excel_EnemyInfoTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Excel_EnemyInfoTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.EnemyInfoTest_classname.Excel_EnemyInfoTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_EnemyInfoTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_EnemyInfoTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_EnemyInfoTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023EnemyInfoTest.proto\022\nHiProtobuf\"I\n\rEne" +
      "myInfoTest\022\n\n\002ID\030\001 \001(\r\022\014\n\004Name\030\002 \001(\t\022\020\n\010" +
      "RootPath\030\003 \001(\t\022\014\n\004Path\030\004 \001(\t\">\n\023Excel_En" +
      "emyInfoTest\022\'\n\004Data\030\001 \003(\0132\031.HiProtobuf.E" +
      "nemyInfoTestBA\n\031com.HiProtobuf.HiProtobu" +
      "fB\027EnemyInfoTest_classname\252\002\nDepth.Datab" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiProtobuf_EnemyInfoTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiProtobuf_EnemyInfoTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_EnemyInfoTest_descriptor,
        new java.lang.String[] { "ID", "Name", "RootPath", "Path", });
    internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HiProtobuf_Excel_EnemyInfoTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_EnemyInfoTest_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
