// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EnemyInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Depth.Data {

  /// <summary>Holder for reflection information generated from EnemyInfo.proto</summary>
  public static partial class EnemyInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for EnemyInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnemyInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9FbmVteUluZm8ucHJvdG8SCkhpUHJvdG9idWYaDENvbW1vbi5wcm90bxoM",
            "VmVjdG9yLnByb3RvIqIBCglFbmVteUluZm8SCgoCSUQYASABKA0SIwoETmFt",
            "ZRgCIAEoCzIVLkhpUHJvdG9idWYuRGVwdGhUZXh0EhAKCFJvb3RQYXRoGAMg",
            "ASgJEgwKBFBhdGgYBCABKAkSIQoEcG9zMRgFIAEoCzITLkhpUHJvdG9idWYu",
            "VmVjdG9yMhIhCgRwb3MyGAYgASgLMhMuSGlQcm90b2J1Zi5WZWN0b3IzIjYK",
            "D0V4Y2VsX0VuZW15SW5mbxIjCgREYXRhGAEgAygLMhUuSGlQcm90b2J1Zi5F",
            "bmVteUluZm9CPQoZY29tLkhpUHJvdG9idWYuSGlQcm90b2J1ZkITRW5lbXlJ",
            "bmZvX2NsYXNzbmFtZaoCCkRlcHRoLkRhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Depth.Localize.CommonReflection.Descriptor, global::Depth.Core.VectorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Depth.Data.EnemyInfo), global::Depth.Data.EnemyInfo.Parser, new[]{ "ID", "Name", "RootPath", "Path", "Pos1", "Pos2" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Depth.Data.Excel_EnemyInfo), global::Depth.Data.Excel_EnemyInfo.Parser, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnemyInfo : pb::IMessage<EnemyInfo> {
    private static readonly pb::MessageParser<EnemyInfo> _parser = new pb::MessageParser<EnemyInfo>(() => new EnemyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnemyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Depth.Data.EnemyInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemyInfo(EnemyInfo other) : this() {
      iD_ = other.iD_;
      name_ = other.name_ != null ? other.name_.Clone() : null;
      rootPath_ = other.rootPath_;
      path_ = other.path_;
      pos1_ = other.pos1_ != null ? other.pos1_.Clone() : null;
      pos2_ = other.pos2_ != null ? other.pos2_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnemyInfo Clone() {
      return new EnemyInfo(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private uint iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private global::Depth.Localize.DepthText name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Depth.Localize.DepthText Name {
      get { return name_; }
      set {
        name_ = value;
      }
    }

    /// <summary>Field number for the "RootPath" field.</summary>
    public const int RootPathFieldNumber = 3;
    private string rootPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RootPath {
      get { return rootPath_; }
      set {
        rootPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Path" field.</summary>
    public const int PathFieldNumber = 4;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pos1" field.</summary>
    public const int Pos1FieldNumber = 5;
    private global::Depth.Core.Vector2 pos1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Depth.Core.Vector2 Pos1 {
      get { return pos1_; }
      set {
        pos1_ = value;
      }
    }

    /// <summary>Field number for the "pos2" field.</summary>
    public const int Pos2FieldNumber = 6;
    private global::Depth.Core.Vector3 pos2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Depth.Core.Vector3 Pos2 {
      get { return pos2_; }
      set {
        pos2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnemyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnemyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if (!object.Equals(Name, other.Name)) return false;
      if (RootPath != other.RootPath) return false;
      if (Path != other.Path) return false;
      if (!object.Equals(Pos1, other.Pos1)) return false;
      if (!object.Equals(Pos2, other.Pos2)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      if (name_ != null) hash ^= Name.GetHashCode();
      if (RootPath.Length != 0) hash ^= RootPath.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (pos1_ != null) hash ^= Pos1.GetHashCode();
      if (pos2_ != null) hash ^= Pos2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ID);
      }
      if (name_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Name);
      }
      if (RootPath.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RootPath);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Path);
      }
      if (pos1_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Pos1);
      }
      if (pos2_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Pos2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ID);
      }
      if (name_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Name);
      }
      if (RootPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RootPath);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (pos1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos1);
      }
      if (pos2_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnemyInfo other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      if (other.name_ != null) {
        if (name_ == null) {
          Name = new global::Depth.Localize.DepthText();
        }
        Name.MergeFrom(other.Name);
      }
      if (other.RootPath.Length != 0) {
        RootPath = other.RootPath;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.pos1_ != null) {
        if (pos1_ == null) {
          Pos1 = new global::Depth.Core.Vector2();
        }
        Pos1.MergeFrom(other.Pos1);
      }
      if (other.pos2_ != null) {
        if (pos2_ == null) {
          Pos2 = new global::Depth.Core.Vector3();
        }
        Pos2.MergeFrom(other.Pos2);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadUInt32();
            break;
          }
          case 18: {
            if (name_ == null) {
              Name = new global::Depth.Localize.DepthText();
            }
            input.ReadMessage(Name);
            break;
          }
          case 26: {
            RootPath = input.ReadString();
            break;
          }
          case 34: {
            Path = input.ReadString();
            break;
          }
          case 42: {
            if (pos1_ == null) {
              Pos1 = new global::Depth.Core.Vector2();
            }
            input.ReadMessage(Pos1);
            break;
          }
          case 50: {
            if (pos2_ == null) {
              Pos2 = new global::Depth.Core.Vector3();
            }
            input.ReadMessage(Pos2);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Excel_EnemyInfo : pb::IMessage<Excel_EnemyInfo> {
    private static readonly pb::MessageParser<Excel_EnemyInfo> _parser = new pb::MessageParser<Excel_EnemyInfo>(() => new Excel_EnemyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Excel_EnemyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Depth.Data.EnemyInfoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Excel_EnemyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Excel_EnemyInfo(Excel_EnemyInfo other) : this() {
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Excel_EnemyInfo Clone() {
      return new Excel_EnemyInfo(this);
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Depth.Data.EnemyInfo> _repeated_data_codec
        = pb::FieldCodec.ForMessage(10, global::Depth.Data.EnemyInfo.Parser);
    private readonly pbc::RepeatedField<global::Depth.Data.EnemyInfo> data_ = new pbc::RepeatedField<global::Depth.Data.EnemyInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Depth.Data.EnemyInfo> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Excel_EnemyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Excel_EnemyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Excel_EnemyInfo other) {
      if (other == null) {
        return;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
