# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnemyInfoTest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EnemyInfoTest.proto',
  package='HiProtobuf',
  syntax='proto3',
  serialized_options=_b('\n\031com.HiProtobuf.HiProtobufB\027EnemyInfoTest_classname\252\002\nDepth.Data'),
  serialized_pb=_b('\n\x13\x45nemyInfoTest.proto\x12\nHiProtobuf\"I\n\rEnemyInfoTest\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08RootPath\x18\x03 \x01(\t\x12\x0c\n\x04Path\x18\x04 \x01(\t\">\n\x13\x45xcel_EnemyInfoTest\x12\'\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x19.HiProtobuf.EnemyInfoTestBA\n\x19\x63om.HiProtobuf.HiProtobufB\x17\x45nemyInfoTest_classname\xaa\x02\nDepth.Datab\x06proto3')
)




_ENEMYINFOTEST = _descriptor.Descriptor(
  name='EnemyInfoTest',
  full_name='HiProtobuf.EnemyInfoTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='HiProtobuf.EnemyInfoTest.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='HiProtobuf.EnemyInfoTest.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RootPath', full_name='HiProtobuf.EnemyInfoTest.RootPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Path', full_name='HiProtobuf.EnemyInfoTest.Path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=108,
)


_EXCEL_ENEMYINFOTEST = _descriptor.Descriptor(
  name='Excel_EnemyInfoTest',
  full_name='HiProtobuf.Excel_EnemyInfoTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='HiProtobuf.Excel_EnemyInfoTest.Data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=172,
)

_EXCEL_ENEMYINFOTEST.fields_by_name['Data'].message_type = _ENEMYINFOTEST
DESCRIPTOR.message_types_by_name['EnemyInfoTest'] = _ENEMYINFOTEST
DESCRIPTOR.message_types_by_name['Excel_EnemyInfoTest'] = _EXCEL_ENEMYINFOTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnemyInfoTest = _reflection.GeneratedProtocolMessageType('EnemyInfoTest', (_message.Message,), {
  'DESCRIPTOR' : _ENEMYINFOTEST,
  '__module__' : 'EnemyInfoTest_pb2'
  # @@protoc_insertion_point(class_scope:HiProtobuf.EnemyInfoTest)
  })
_sym_db.RegisterMessage(EnemyInfoTest)

Excel_EnemyInfoTest = _reflection.GeneratedProtocolMessageType('Excel_EnemyInfoTest', (_message.Message,), {
  'DESCRIPTOR' : _EXCEL_ENEMYINFOTEST,
  '__module__' : 'EnemyInfoTest_pb2'
  # @@protoc_insertion_point(class_scope:HiProtobuf.Excel_EnemyInfoTest)
  })
_sym_db.RegisterMessage(Excel_EnemyInfoTest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
