# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnemyInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EnemyInfo.proto',
  package='HiProtobuf',
  syntax='proto3',
  serialized_options=_b('\n\031com.HiProtobuf.HiProtobufB\023EnemyInfo_classname\252\002\nDepth.Data'),
  serialized_pb=_b('\n\x0f\x45nemyInfo.proto\x12\nHiProtobuf\"E\n\tEnemyInfo\x12\n\n\x02ID\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08RootPath\x18\x03 \x01(\t\x12\x0c\n\x04Path\x18\x04 \x01(\t\"6\n\x0f\x45xcel_EnemyInfo\x12#\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x15.HiProtobuf.EnemyInfoB=\n\x19\x63om.HiProtobuf.HiProtobufB\x13\x45nemyInfo_classname\xaa\x02\nDepth.Datab\x06proto3')
)




_ENEMYINFO = _descriptor.Descriptor(
  name='EnemyInfo',
  full_name='HiProtobuf.EnemyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='HiProtobuf.EnemyInfo.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='HiProtobuf.EnemyInfo.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RootPath', full_name='HiProtobuf.EnemyInfo.RootPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Path', full_name='HiProtobuf.EnemyInfo.Path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=100,
)


_EXCEL_ENEMYINFO = _descriptor.Descriptor(
  name='Excel_EnemyInfo',
  full_name='HiProtobuf.Excel_EnemyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='HiProtobuf.Excel_EnemyInfo.Data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=156,
)

_EXCEL_ENEMYINFO.fields_by_name['Data'].message_type = _ENEMYINFO
DESCRIPTOR.message_types_by_name['EnemyInfo'] = _ENEMYINFO
DESCRIPTOR.message_types_by_name['Excel_EnemyInfo'] = _EXCEL_ENEMYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnemyInfo = _reflection.GeneratedProtocolMessageType('EnemyInfo', (_message.Message,), {
  'DESCRIPTOR' : _ENEMYINFO,
  '__module__' : 'EnemyInfo_pb2'
  # @@protoc_insertion_point(class_scope:HiProtobuf.EnemyInfo)
  })
_sym_db.RegisterMessage(EnemyInfo)

Excel_EnemyInfo = _reflection.GeneratedProtocolMessageType('Excel_EnemyInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXCEL_ENEMYINFO,
  '__module__' : 'EnemyInfo_pb2'
  # @@protoc_insertion_point(class_scope:HiProtobuf.Excel_EnemyInfo)
  })
_sym_db.RegisterMessage(Excel_EnemyInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
