/****************************************************************************
 * Description: 
 * 
 * Document: https://github.com/hiramtan/HiProtobuf
 * Author: hiramtan@live.com
 ****************************************************************************/

using HiFramework.Assert;
using HiFramework.Log;
using OfficeOpenXml;
using System.IO;
using System.Collections.Generic;

namespace HiProtobuf.Lib
{
    internal class ProtoHandler
    {
        public static Dictionary<string, string> ClassNamespaceMap = new Dictionary<string, string>();
        public ProtoHandler()
        {
            var path = Settings.Export_Folder + Settings.proto_folder;
            if (Directory.Exists(path))
            {
                ClearReadOnlyAttributes(path);
                Directory.Delete(path, true);
            }
            Directory.CreateDirectory(path);
        }

        private static void ClearReadOnlyAttributes(string directoryPath)
        {
            var files = Directory.GetFiles(directoryPath, "*", SearchOption.AllDirectories);
            foreach (var file in files)
            {
                var attributes = File.GetAttributes(file);
                if ((attributes & FileAttributes.ReadOnly) == 0)
                {
                    continue;
                }

                Log.Warning($"检测到只读文件，正在清除只读属性：{file}");
                File.SetAttributes(file, attributes & ~FileAttributes.ReadOnly);
            }
        }

        public void Process()
        {
            GenerateCommonProto();
            GenerateVectorProto();
            //递归查询
            string[] files = Directory.GetFiles(Settings.Excel_Folder, "*.xlsx", SearchOption.AllDirectories);
            for (int i = 0; i < files.Length; i++)
            {
                var path = files[i];
                if (path.Contains("~$"))//已打开的表格格式
                {
                    continue;
                }
                ProcessExcel(path);
            }
        }

        void GenerateCommonProto()
        {
            var path = Settings.Export_Folder + Settings.proto_folder + "/Common.proto";
            var content = @"
// This is auto generated by HiProtobuf
// Common types

syntax = ""proto3"";
package HiProtobuf;

option csharp_namespace = ""Depth.Localize"";

message DepthText
{
    uint32 id = 1;
    string text = 2;
}
";
            File.WriteAllText(path, content);
        }

        void GenerateVectorProto()
        {
            var path = Settings.Export_Folder + Settings.proto_folder + "/Vector.proto";
            var content = @"
// This is auto generated by HiProtobuf
// Vector types

syntax = ""proto3"";
package HiProtobuf;

option csharp_namespace = ""Depth.Core"";

message Vector2
{
    float x = 1;
    float y = 2;
}

message Vector3
{
    float x = 1;
    float y = 2;
    float z = 3;
}
";
            File.WriteAllText(path, content);
        }

        void ProcessExcel(string path)
        {
            AssertThat.IsNotNullOrEmpty(path);
            var fileInfo = new FileInfo(path);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (ExcelPackage excelPackage = new ExcelPackage(fileInfo))
            {
                var worksheets = excelPackage.Workbook.Worksheets;
                var strNameSpace = Path.GetFileNameWithoutExtension(path);
                foreach (var worksheet in worksheets)
                {
                    AssertThat.IsNotNull(worksheet, "Excel's sheet is null");
                    var strNameClass = worksheet.Name;
                    // 记录 class-namespace 映射
                    if (!ClassNamespaceMap.ContainsKey(strNameClass))
                        ClassNamespaceMap.Add(strNameClass, strNameSpace);
                    new ProtoGenerater(strNameSpace, strNameClass, worksheet).Process();
                }
            }
        }
    }
}
